name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag janole/laravel-nginx-postgres:0-master
    - name: Push the Docker image
      env: 
        user: ${{ secrets.DOCKER_USERNAME }}
        pass: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u "${USER}" -p "${PASS}" && docker push janole/laravel-nginx-postgres:0-master && docker logout
